Fe ahmadyahya
muhmlna/OK-OCE-Website pull request #9
Opened 2024-04-24 07:34 UTC by Ahmadyahya123

Tambah 3 Laman " Brandlokal, masjid pemebrdaya, modal berkah"

2024-04-24 07:56 UTC, Ahmadyahya123 commented
"Membuat 3 Laman : https://github.com/muhmlna/OK-OCE-Website/pull/9/commits/72cbbd4849c77b79fbf4c2874a751296be0d7b7b"

2024-04-25 14:52 UTC, muhmlna requested changes

2024-04-25 14:52 UTC, muhmlna commented on src/containers/LokalBrand.js
> +import Lokalbrand1 from "../asset/img/lokalbrand/lokalbrand1.PNG";
@img ubah dlu ini, @Ahmadyahya123

2024-04-26 08:52 UTC, muhmlna approved these changes

2024-04-26 08:52 UTC, merged